name: deploy service to staging environment (GCP)

on:
  push:
    branches:
      - main

env:
  STAGE: develop
  REGION: asia-southeast1
  MIN_INSTANCES: 0
  APP_NAME: ${{ vars.APP_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Configure Docker
        run: gcloud auth configure-docker asia.gcr.io

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Tag Image and Set Environment
        id: set_env
        run: |
          echo "COMMIT_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "SERVICE_NAME=$STAGE-da-mock-server" >> $GITHUB_ENV

      - name: Set Image Name
        id: set_image_name
        run: |
          echo "IMAGE_NAME=asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ env.COMMIT_VERSION }}" >> $GITHUB_ENV
      
      - name: Build Image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} . --build-arg APP_NAME=$APP_NAME --build-arg STAGE=$STAGE
          
      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}

      - name: Deploy Docker image
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.IMAGE_NAME }} \
            --region $REGION \
            --min-instances $MIN_INSTANCES \
            --set-env-vars "STAGE=$STAGE" \
            --platform managed \
            --allow-unauthenticated
